config/routes.rb
CityguideApp::Application.routes.draw do
  devise_for :users
   get 'tags/:tag', to: 'attractions#index', as: :tag
  root "home#index"
  resources :attractions do
    put :favorite, on: :member
  end

end

app/models/attraction.rb
class Attraction < ActiveRecord::Base
	searchable do
		text :title
		text :tag_list
	end
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	acts_as_taggable	
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :attractions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
	def index
		if params[:tag]
    		@attractions = Attraction.tagged_with(params[:tag])
    	elsif params[:q]
    		query = params[:q]
    		@search = Attraction.search do 
    			keywords query
    		end
    		@attractions = @search.results
		else
			@attractions = Attraction.all
		end
	end

	def new
		@attraction = Attraction.new
	end

	def create
		@attraction = Attraction.new(attraction_params)
		respond_to do |format|
      		if @attraction.save
        		format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        		format.json { render action: 'show', status: :created, location: @attraction }
     		else
        		format.html { render action: 'new' }
        		format.json { render json: @attraction.errors, status: :unprocessable_entity }
      		end
    	end
 	end

	def show
		@attraction = Attraction.find(params[:id])
	end

	def edit
		@attraction = Attraction.find(params[:id])
	end

	def update
		@attraction = Attraction.find(params[:id])

		@attraction.update_attributes(attraction_params)
		redirect_to @attraction
	end
	
	def favorite
		type = params[:type]
		@attraction = Attraction.find(params[:id])
		if type == "add"
			current_user.attractions << @attraction
			redirect_to :back, notice: "You have added #{@attraction.title} to your trip"
		elsif type == "remove"
			current_user.attractions.delete(@attraction)
			redirect_to :back, notice: "You have removed #{@attraction.title} from your trip"
		else 
			redirect_to :back, notice: 'Nothing happened.'
		end
	end

	def destroy
		@attraction = Attraction.find(params[:id])
		@attraction.destroy
		redirect_to attractions_path(@attraction)
	end


	private
	def attraction_params
		params.require(:attraction).permit(:title, :content, :price, :tagline, :tag_list, :address, :link, :avatar, :latitude, :longitude)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :authenticate_user!
	def index
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attractions/edit.html.erb
<%= form_for @attraction, :html => { :multipart => true } do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="area">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
 <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br>
    <%= f.text_field :tagline %>
  </div>
  <div class="area">
    <%= f.label :tags %><br>
    <%= f.text_area :tags %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.number_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.number_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attractions/index.html.erb
<body>
  <h1> Welcome to XXX </h1>
  <h4> your portal to the unexplored </h4>

  <div class="row">
    <div class="large-12 columns">
 
      <!-- Navigation -->
 
        <ul class="button-group">
          <li><a href="#" class="button">Nav Item 1</a></li>
          <li><a href="#" class="button">Nav Item 2</a></li>
          <li><a href="#" class="button">Nav Item 3</a></li>
        </ul>
 
      <!-- End Navigation -->

    <div class="column">
 <!-- Nav Sidebar -->
    <!-- This is source ordered to be pulled to the left on larger screens -->
      <div class="large-3 columns ">
      <h5>MY TRIP TO PROVIDENCE</h5>
        <div class="panel">
          <% current_user.attractions.each do |attraction| %>
            <h6><%= link_to attraction.title, attraction_path(attraction) %></h6>
            <%= link_to image_tag(attraction.avatar.url), attraction_path(attraction) %>
            <%= link_to favorite_attraction_path(attraction, type: "remove"), method: :put do%>
                <i class="fi-minus"></i>
             <% end %>
          <% end %>
         </div>
    
      </div>
 
 
      <!-- Search Bar -->
 
        <div class="row">
 
          <div class="large-12 columns">
            <div class="radius panel">
 
            <form>
              <div class="row collapse">
 
                <div class="large-10 small-8 columns">
                  <%=text_field_tag "q", params[:q], placeholder: "Special interests or must-sees?" %>
                </div>
                <div class="large-2 small-3 columns">
                  <input type="submit" value="TAKE ME THERE" class="postfix button expand">
                </div>
 
              </div>
            </form>
 
          </div>
          </div>
 
        </div>
        <% if @search %>
  <h5> <%= @search.total %> results </h5>
<% end %>
 
      <!-- End Search Bar -->
 
 
      <!-- Thumbnails -->
 
        <div class="row">
 
          <div class="large-12 show-for-small columns">
          <h3>Header</h3><hr>
        </div>

        <% @attractions.each do |attraction| %>
          <div class="large-3 small-6 columns">
            <div class="panel">
               <h6><%= attraction.tagline %></h6>
                 <%= link_to image_tag(attraction.avatar.url), attraction_path(attraction) %>
             <h6><%= attraction.title %></h6>
             <%= link_to favorite_attraction_path(attraction, type: "add"), method: :put do %>
                <i class="fi-plus"></i>
             <% end %>
            </div>
          </div>
        <% end %>
 
        </div>


 
      <!-- End Thumbnails -->
 
 
      <!-- Footer -->
 
        <footer class="row">
        <div class="large-12 columns"><hr />
            <div class="row">
 
              <div class="large-6 columns">
                  <p>© Copyright no one at all. Go to town.</p>
              </div>
 
              <div class="large-6 columns">
                  <ul class="inline-list right">
                    <li><a href="#">Link 1</a></li>
                    <li><a href="#">Link 2</a></li>
                    <li><a href="#">Link 3</a></li>
                    <li><a href="#">Link 4</a></li>
                  </ul>
              </div>
 
            </div>
        </div>
      </footer>
 
      <!-- End Footer -->
 
 
    </div>
  </div>

<%= link_to "Add a new attraction", new_attraction_path %>
<br/>
<br/>
<table>
  <table border="1" 
cellpadding="10">
	<tr>
		<th>Title</th>
		<th>Tagline</th>
    <th>Tags</th>
<% @attractions.each do |attraction| %>
<tr>
<td><%= link_to attraction.title, attraction_path(attraction) %></td>
<td><%= attraction.tagline %></td>
<td><%= raw attraction.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
<td><%= link_to "Add to Trip", favorite_attraction_path(attraction, type: "add"), method: :put %></td>
<td><%= link_to "Edit", edit_attraction_path(attraction) %></td>
<td> <%= link_to "Destroy", attraction_path(attraction), method: :delete, data: {confirm: "Are you sure?"} %></td>
</tr>
<% end %>
</table>


  <h3> My Trip to Providence </h3>
<table>
  <table border="1" 
cellpadding="10">
  <tr>
    <th>Title</th>
    <th>Tagline</th>
    <th>Tags</th>
<% current_user.attractions.each do |attraction| %>
<tr>
<td><%= link_to attraction.title, attraction_path(attraction) %></td>
<td><%= attraction.tagline %></td>
<td><%= raw attraction.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
<td><%= link_to "Remove from Trip", favorite_attraction_path(attraction, type: "remove"), method: :put %></td>
</tr>
<% end %>
</table>
<% current_user.attractions.each do |attraction| %>
<div id="map">
  <%= map(:center => {
    :latlng => [41.823550, -71.422132],
    :zoom => 14
  },
  :markers => [
    {
       :latlng => [attraction.latitude, attraction.longitude]
    }
  ]
) %>
</div>
<% end %>
</body>

app/views/attractions/new.html.erb
<%= form_for @attraction, :url => attractions_path, :html => { :multipart => true } do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="area">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
 <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br>
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.number_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.number_field :longitude %>
  </div>
<div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attractions/show.html.erb
<h1><%= @attraction.title %> </h1>
<%= image_tag @attraction.avatar.url(:medium) %>

<div id="map">
	<%= map(:center => {
    :latlng => [@attraction.latitude, @attraction.longitude],
    :zoom => 18
  },
  :markers => [
    {
       :latlng => [@attraction.latitude, @attraction.longitude],
       :popup => @attraction.title
    }
  ]
) %>
</div>

<p> <b>Price: </b> $ <%= @attraction.price %> </p>
<p> <b>Address: </b> <%= @attraction.address %> </p>
<p> <b>Website: </b> <%= @attraction.link %> </p>
<p> <b>Tags: </b> <%= raw @attraction.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %> </p>
<h2> About </h2> <p> <%= @attraction.content %> </p>

 <%= link_to "Add to Trip",   favorite_attraction_path(@attraction, type: "add"), method: :put %> |
 <%= link_to "Remove from Trip", favorite_attraction_path(@attraction, type: "remove"), method: :put %>
<br/>
<br/>
<%= link_to "Back", attractions_path %> |
<%= link_to "Edit", edit_attraction_path %> |
<%= link_to "Destroy", attraction_path(@attraction), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/home/index.html.erb
<h1> Welcome to XXX </h1>
<h4> your portal to the unexplored </h4>


<form class="navbar-form navbar-left" role="search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Enter any special interests or must-sees">
  </div>
  <button type="submit" class="btn btn-default">TAKE ME THERE</button>
</form>
<br/>
<%= link_to "See all attractions", attractions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<% if user_signed_in? %>
		<p class = "user">You are signed in as <%= current_user.email %> </p>
		<%= link_to "Log out", destroy_user_session_path, method: :delete %>
	<% end %>
 	<p class="notice"><%= notice %></p>
	 <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>